version: '3.8'

services:
  nfscan-automation:
    build: .
    container_name: nfscan-automation
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BOSCH_ID=${BOSCH_ID}
      - BOSCH_PASSWORD=${BOSCH_PASSWORD}
      - LOG_LEVEL=info
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=nfscan-automation"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  coolify:
    external: true
